
// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { loadEnvFile } from "node:process";
try { loadEnvFile(".env.local"); } catch {}
import { defineConfig, env } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  engine: "classic",
  datasource: {
    url: env("DIRECT_URL"),
  },
});
